use crate::get_mouse_pos;

pub type Position = (i32, i32);

#[derive(Eq, PartialEq, Copy, Clone, Debug)]
pub enum Key {
    Char(char),
    UNKNOWN(u8),

    LBUTTON(Position),
    RBUTTON(Position),
    MBUTTON(Position),
    XBUTTON1(Position),
    XBUTTON2(Position),

    CANCEL,
    BACK,
    TAB,
    CLEAR,
    RETURN,
    SHIFT,
    CONTROL,
    MENU,
    PAUSE,
    CAPITAL,
    KANA, // KANA,HANGUEL,HANGUL
    JUNJA,
    FINAL,
    HANJA, // HANJA,KANJI
    ESCAPE,
    CONVERT,
    NONCONVERT,
    ACCEPT,
    MODECHANGE,
    SPACE,
    PRIOR,
    NEXT,
    END,
    HOME,
    LEFT,
    UP,
    RIGHT,
    DOWN,
    SELECT,
    PRINT,
    EXECUTE,
    SNAPSHOT,
    INSERT,
    DELETE,
    HELP,
    LWIN,
    RWIN,
    APPS,
    SLEEP,
    NUMPAD0,
    NUMPAD1,
    NUMPAD2,
    NUMPAD3,
    NUMPAD4,
    NUMPAD5,
    NUMPAD6,
    NUMPAD7,
    NUMPAD8,
    NUMPAD9,
    MULTIPLY,
    ADD,
    SEPARATOR,
    SUBTRACT,
    DECIMAL,
    DIVIDE,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    NUMLOCK,
    SCROLL,
    LSHIFT,
    RSHIFT,
    LCONTROL,
    RCONTROL,
    LMENU,
    RMENU,
    BROWSER_BACK,
    BROWSER_FORWARD,
    BROWSER_REFRESH,
    BROWSER_STOP,
    BROWSER_SEARCH,
    BROWSER_FAVORITES,
    BROWSER_HOME,
    VOLUME_MUTE,
    VOLUME_DOWN,
    VOLUME_UP,
    MEDIA_NEXT_TRACK,
    MEDIA_PREV_TRACK,
    MEDIA_STOP,
    MEDIA_PLAY_PAUSE,
    LAUNCH_MAIL,
    LAUNCH_MEDIA_SELECT,
    LAUNCH_APP1,
    LAUNCH_APP2,
    OEM_1,
    OEM_PLUS,
    OEM_COMMA,
    OEM_MINUS,
    OEM_PERIOD,
    OEM_2,
    OEM_3,
    OEM_4,
    OEM_5,
    OEM_6,
    OEM_7,
    OEM_8,
    OEM_102,
    PROCESSKEY,
    ATTN,
    CRSEL,
    EXSEL,
    EREOF,
    PLAY,
    ZOOM,
    NONAME,
    PA1,
    OEM_CLEAR,
}

impl Key {
    pub fn from_u8(code: u8) -> Self {
        match code {
            65 ... 90 => Key::Char(code as char),

            0x01 => Key::LBUTTON(get_mouse_pos()),
            0x02 => Key::RBUTTON(get_mouse_pos()),
            0x03 => Key::CANCEL,
            0x04 => Key::MBUTTON(get_mouse_pos()),
            0x05 => Key::XBUTTON1(get_mouse_pos()),
            0x06 => Key::XBUTTON2(get_mouse_pos()),
            0x08 => Key::BACK,
            0x09 => Key::TAB,
            0x0C => Key::CLEAR,
            0x0D => Key::RETURN,
            0x10 => Key::SHIFT,
            0x11 => Key::CONTROL,
            0x12 => Key::MENU,
            0x13 => Key::PAUSE,
            0x14 => Key::CAPITAL,
            0x15 => Key::KANA,
            0x17 => Key::JUNJA,
            0x18 => Key::FINAL,
            0x19 => Key::HANJA,
            0x1B => Key::ESCAPE,
            0x1C => Key::CONVERT,
            0x1D => Key::NONCONVERT,
            0x1E => Key::ACCEPT,
            0x1F => Key::MODECHANGE,
            0x20 => Key::SPACE,
            0x21 => Key::PRIOR,
            0x22 => Key::NEXT,
            0x23 => Key::END,
            0x24 => Key::HOME,
            0x25 => Key::LEFT,
            0x26 => Key::UP,
            0x27 => Key::RIGHT,
            0x28 => Key::DOWN,
            0x29 => Key::SELECT,
            0x2A => Key::PRINT,
            0x2B => Key::EXECUTE,
            0x2C => Key::SNAPSHOT,
            0x2D => Key::INSERT,
            0x2E => Key::DELETE,
            0x2F => Key::HELP,
            0x5B => Key::LWIN,
            0x5C => Key::RWIN,
            0x5D => Key::APPS,
            0x5F => Key::SLEEP,
            0x60 => Key::NUMPAD0,
            0x61 => Key::NUMPAD1,
            0x62 => Key::NUMPAD2,
            0x63 => Key::NUMPAD3,
            0x64 => Key::NUMPAD4,
            0x65 => Key::NUMPAD5,
            0x66 => Key::NUMPAD6,
            0x67 => Key::NUMPAD7,
            0x68 => Key::NUMPAD8,
            0x69 => Key::NUMPAD9,
            0x6A => Key::MULTIPLY,
            0x6B => Key::ADD,
            0x6C => Key::SEPARATOR,
            0x6D => Key::SUBTRACT,
            0x6E => Key::DECIMAL,
            0x6F => Key::DIVIDE,
            0x70 => Key::F1,
            0x71 => Key::F2,
            0x72 => Key::F3,
            0x73 => Key::F4,
            0x74 => Key::F5,
            0x75 => Key::F6,
            0x76 => Key::F7,
            0x77 => Key::F8,
            0x78 => Key::F9,
            0x79 => Key::F10,
            0x7A => Key::F11,
            0x7B => Key::F12,
            0x7C => Key::F13,
            0x7D => Key::F14,
            0x7E => Key::F15,
            0x7F => Key::F16,
            0x80 => Key::F17,
            0x81 => Key::F18,
            0x82 => Key::F19,
            0x83 => Key::F20,
            0x84 => Key::F21,
            0x85 => Key::F22,
            0x86 => Key::F23,
            0x87 => Key::F24,
            0x90 => Key::NUMLOCK,
            0x91 => Key::SCROLL,
            0xA0 => Key::LSHIFT,
            0xA1 => Key::RSHIFT,
            0xA2 => Key::LCONTROL,
            0xA3 => Key::RCONTROL,
            0xA4 => Key::LMENU,
            0xA5 => Key::RMENU,
            0xA6 => Key::BROWSER_BACK,
            0xA7 => Key::BROWSER_FORWARD,
            0xA8 => Key::BROWSER_REFRESH,
            0xA9 => Key::BROWSER_STOP,
            0xAA => Key::BROWSER_SEARCH,
            0xAB => Key::BROWSER_FAVORITES,
            0xAC => Key::BROWSER_HOME,
            0xAD => Key::VOLUME_MUTE,
            0xAE => Key::VOLUME_DOWN,
            0xAF => Key::VOLUME_UP,
            0xB0 => Key::MEDIA_NEXT_TRACK,
            0xB1 => Key::MEDIA_PREV_TRACK,
            0xB2 => Key::MEDIA_STOP,
            0xB3 => Key::MEDIA_PLAY_PAUSE,
            0xB4 => Key::LAUNCH_MAIL,
            0xB5 => Key::LAUNCH_MEDIA_SELECT,
            0xB6 => Key::LAUNCH_APP1,
            0xB7 => Key::LAUNCH_APP2,
            0xBA => Key::OEM_1,
            0xBB => Key::OEM_PLUS,
            0xBC => Key::OEM_COMMA,
            0xBD => Key::OEM_MINUS,
            0xBE => Key::OEM_PERIOD,
            0xBF => Key::OEM_2,
            0xC0 => Key::OEM_3,
            0xDB => Key::OEM_4,
            0xDC => Key::OEM_5,
            0xDD => Key::OEM_6,
            0xDE => Key::OEM_7,
            0xDF => Key::OEM_8,
            0xE2 => Key::OEM_102,
            0xE5 => Key::PROCESSKEY,
            0xF6 => Key::ATTN,
            0xF7 => Key::CRSEL,
            0xF8 => Key::EXSEL,
            0xF9 => Key::EREOF,
            0xFA => Key::PLAY,
            0xFB => Key::ZOOM,
            0xFC => Key::NONAME,
            0xFD => Key::PA1,
            0xFE => Key::OEM_CLEAR,

            _ => Key::UNKNOWN(code)
        }
    }
}
